// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjDM2kUDKZ4Cs7m8MbZLeUEWNSimw74w',
    appId: '1:788222832990:web:bd41133b6038131d681fcf',
    messagingSenderId: '788222832990',
    projectId: 'reloop-831da',
    authDomain: 'reloop-831da.firebaseapp.com',
    storageBucket: 'reloop-831da.firebasestorage.app',
    measurementId: 'G-ECWV1Y9GP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLDoiMRTXaAUVfpm5fFvFZCF4-S3coBU',
    appId: '1:788222832990:android:f071d33cd27e1473681fcf',
    messagingSenderId: '788222832990',
    projectId: 'reloop-831da',
    storageBucket: 'reloop-831da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo716iEVJmvWU0kOAFTq2JUD6akOlzxJE',
    appId: '1:788222832990:ios:722bcfef997fa0dd681fcf',
    messagingSenderId: '788222832990',
    projectId: 'reloop-831da',
    storageBucket: 'reloop-831da.firebasestorage.app',
    iosBundleId: 'com.example.reloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo716iEVJmvWU0kOAFTq2JUD6akOlzxJE',
    appId: '1:788222832990:ios:722bcfef997fa0dd681fcf',
    messagingSenderId: '788222832990',
    projectId: 'reloop-831da',
    storageBucket: 'reloop-831da.firebasestorage.app',
    iosBundleId: 'com.example.reloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOjDM2kUDKZ4Cs7m8MbZLeUEWNSimw74w',
    appId: '1:788222832990:web:f59a5a815bab1f26681fcf',
    messagingSenderId: '788222832990',
    projectId: 'reloop-831da',
    authDomain: 'reloop-831da.firebaseapp.com',
    storageBucket: 'reloop-831da.firebasestorage.app',
    measurementId: 'G-PT0NJ8S30T',
  );
}
